name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    name: Test Backend (.NET)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Restore dependencies
      run: dotnet restore backend/FileViewer.Api/FileViewer.Api.csproj
    
    - name: Build
      run: dotnet build backend/FileViewer.Api/FileViewer.Api.csproj --no-restore
    
    - name: Test
      run: dotnet test backend/FileViewer.Api/FileViewer.Api.csproj --no-build --verbosity normal

  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend (React)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      working-directory: frontend
    
    - name: Build
      run: npm run build
      working-directory: frontend

  lint-and-format:
    runs-on: ubuntu-latest
    name: Lint and Format Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend
    
    - name: Check TypeScript
      run: npx tsc --noEmit
      working-directory: frontend

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run npm audit
      run: npm audit --audit-level moderate
      working-directory: frontend
      continue-on-error: true
    
    - name: Run .NET security scan
      run: dotnet list backend/FileViewer.Api/FileViewer.Api.csproj package --vulnerable
      continue-on-error: true
